### ISSUE TITLE
Custom language support

### ISSUE THREAD

**Issue by raproid** [readmeio/oas-to-snippet#162]
Hi!

Do I understand correctly that this is the component that translates an API request sample into various languages?
If so, is it possible to add a custom language?
For our project, we need to add "AnkrJS" as a language.
Can we do it via the frontend, somewhere in the admin panel of our Readme project?
If no, can we add it any other way and how?
<img width="516" alt="Screenshot 2023-01-31 at 7 20 13 PM" src="https://user-images.githubusercontent.com/22454517/215759591-79d46797-5dcc-49d7-be7e-6993ad735fc3.png">

**Comment by erunion** [comment]
Closing this in favor of https://github.com/readmeio/httpsnippet/issues/152
