### ISSUE TITLE
PHP: Guzzle

### ISSUE THREAD

**Issue by philsturgeon** [readmeio/oas-to-snippet#174]
Hey folks, thanks for making this cool script! 

PHP users generally don't use Curl, it's a mess, but Guzzle is massively popular. Could you pop a template in for that?

**Comment by domharrington** [comment]
Hey! We already support Guzzle, and it's also the default! 👍 https://github.com/readmeio/oas-to-snippet/blob/16f308d41bfa0008f488c29809b897b5bf4ddd4c/src/supportedLanguages.ts#L184

You can try it out with the following code:

```js
const Oas = require('oas');
const { oasToSnippet } = require('@readme/oas-to-snippet');

const oas = new Oas.default({
  openapi: '3.0.0',
  info: {
    title: 'spec',
    version: '1.0.0',
  },
  servers: [{ url: 'https://httpbin.org' }],
  paths: {
    '/': {
      get: {
        parameters: [],
        responses: {
          200: {
            description: 'desc',
          },
        },
      },
    },
  },
});

const { code } = oasToSnippet(oas, oas.operation('/', 'get'), {}, {}, 'php');
console.log(code);
```

This outputs:

```php
<?php
require_once('vendor/autoload.php');

$client = new \GuzzleHttp\Client();

$response = $client->request('GET', 'https://httpbin.org/');

echo $response->getBody();
```

Lmk if you have any other questions!

**Comment by erunion** [comment]
Noticed that our README didn't note that we supported Guzzle so I've resolved that in https://github.com/readmeio/oas-to-snippet/commit/a40c1d0774e9e0cdd2a65ae4afab82b0eb43a1ca. Thanks!
